#!/bin/bash
set -x

ENGINE=${1:-vllm}

export HF_ENDPOINT="https://hf-mirror.com"
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
DATA_ROOT=/devsft_AFS/hanxiaoli/verl_data

TRAIN_DATA="$DATA_ROOT/searchR1_processed_direct/train.parquet"
VAL_DATA="$DATA_ROOT/searchR1_processed_direct/test.parquet"


CHECKPOINT_CONTENTS=['model','optimizer','extra']

EXPERIMENT_NAME="ablate_deceptive_search_mm_qwen4b_judge_no_cot"

# CoT ablation using the existing constrained top-k scorer and non-thinking judge template.
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$TRAIN_DATA \
    data.val_files=$VAL_DATA \
    data.train_batch_size=120 \
    data.val_batch_size=512 \
    data.max_prompt_length=2048 \
    data.max_response_length=512 \
    data.filter_overlong_prompts=True \
    data.truncation='left' \
    data.return_raw_chat=True \
    actor_rollout_ref.model.path=checkpoints/verl_deceptive_search/grpo_deceptive_search_qwen3_4b/global_step_190/actor/huggingface \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.chat_template_kwargs.enable_thinking=True \
    actor_rollout_ref.actor.checkpoint.contents=$CHECKPOINT_CONTENTS \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.02 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.use_invalid_action_penalty=True \
    actor_rollout_ref.actor.invalid_action_penalty_coef=0.01 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
    monitor_rollout_ref.enable=True \
    monitor_rollout_ref.enable_train_monitor=True \
    monitor_rollout_ref.actor_cost_threshold=0.2 \
    monitor_rollout_ref.rollout.n=1 \
    monitor_rollout_ref.algorithm.adv_estimator=reinforce_plus_plus \
    monitor_rollout_ref.data.truncation='left' \
    monitor_rollout_ref.model.path=Qwen/Qwen3-4B \
    monitor_rollout_ref.model.use_remove_padding=True \
    monitor_rollout_ref.model.enable_gradient_checkpointing=True \
    monitor_rollout_ref.model.chat_template_kwargs.enable_thinking=False \
    monitor_rollout_ref.monitor.optim.lr=1e-6 \
    monitor_rollout_ref.monitor.optim.lr_warmup_steps_ratio=0.1 \
    monitor_rollout_ref.monitor.use_kl_loss=True \
    monitor_rollout_ref.monitor.kl_loss_coef=0.001 \
    monitor_rollout_ref.monitor.kl_loss_type=low_var_kl \
    monitor_rollout_ref.monitor.entropy_coeff=0.005 \
    monitor_rollout_ref.monitor.fsdp_config.param_offload=True \
    monitor_rollout_ref.monitor.fsdp_config.optimizer_offload=True \
    monitor_rollout_ref.monitor.use_invalid_action_penalty=True \
    monitor_rollout_ref.monitor.invalid_action_penalty_coef=0.01 \
    monitor_rollout_ref.monitor.ppo_mini_batch_size=42 \
    monitor_rollout_ref.monitor.ppo_micro_batch_size_per_gpu=2 \
    monitor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
    monitor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    monitor_rollout_ref.rollout.name=$ENGINE \
    monitor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    monitor_rollout_ref.rollout.enable_chunked_prefill=False \
    monitor_rollout_ref.rollout.enforce_eager=False \
    monitor_rollout_ref.rollout.free_cache_engine=False \
    monitor_rollout_ref.rollout.val_kwargs.temperature=1.0 \
    monitor_rollout_ref.rollout.val_kwargs.do_sample=False \
    monitor_rollout_ref.ref.fsdp_config.param_offload=True \
    monitor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
    reward_model.reward_manager=actor_monitor \
    judge_model.backend=constrained_logits \
    judge_model.template_name=strict5 \
    judge_model.model.path=Qwen/Qwen3-8B \
    judge_model.model.chat_template_kwargs.enable_thinking=False \
    judge_model.constrained_top_k=1 \
    judge_model.max_prompt_length=8192 \
    judge_model.truncation=error \
    judge_model.micro_batch_size_per_gpu=4 \
    algorithm.use_kl_in_reward=False \
    algorithm.gamma=0.95 \
    env.env_name=deceptive_search \
    env.seed=0 \
    env.max_steps=4 \
    env.rollout.n=5 \
    env.history_length=4 \
    env.deceptive_search.search_url='http://127.0.0.1:8000/retrieve' \
    env.deceptive_search.reward_correct=1.0 \
    trainer.logger=['console','wandb'] \
    trainer.log_val_generations=2 \
    trainer.log_distributions=True \
    trainer.project_name='verl_deceptive_search' \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.n_gpus_per_node_monitor=3 \
    trainer.nnodes_monitor=1 \
    trainer.judge_pool_mode=separate \
    trainer.n_gpus_per_node_judge=1 \
    trainer.nnodes_judge=1 \
    trainer.save_steps='[30,40,80]' \
    trainer.test_freq=81 \
    trainer.total_epochs=1 \
    trainer.val_before_train=False "$@"